### ISSUE TITLE
Figure out how to link to docs for linter rules

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/zed-rego#8]
A huge part of Regal's value is in its documentation. Particularly for people learning Rego, the short descriptions provided for the rules may tell the "what", but only in an extremely limited form, and certainly not the "why". 

Screenshot showing typical violation description on hover:

<img width="408" alt="Screenshot 2024-05-29 at 09 10 13" src="https://github.com/StyraInc/zed-rego/assets/510711/fcea753f-5917-4524-9c67-298479bd2606">

Notice how not even the _rule name_ is displayed here, making it unlikely that the user is even able to find it by searching online.

The "Problems" view is a little more detailed, as it at least will display the name of the rule, but that's about it:

<img width="1254" alt="Screenshot 2024-05-29 at 09 10 42" src="https://github.com/StyraInc/zed-rego/assets/510711/aebf37cc-909d-4602-959c-3ecda9fc1f83">

We should try and figure out if there's any way that we can get Zed to display links to the Regal rules documentation, on hover and in the problems view. If that's not possible, we need to make the best of what we have, and adapt the messages so that at least the name of each rule is displayed in all views, and that the README/docs make it _very_ clear how to find the documentation for any given linter rule.

Sadly, the **Code Action** "Go to documentation for rule X" is similarly broken, as Zed doesn't appear to have a built-in command for opening links, like `vscode.open` in VS Code.

One place where it looks like we _can_ reliably show links is in the hover provider: 

<img width="747" alt="Screenshot 2024-05-29 at 09 46 43" src="https://github.com/StyraInc/zed-rego/assets/510711/898cc07c-f88d-4535-a662-2e2b59135583">

Shoehorning linter violations in there would be a huge hack, but... 

Let's try and find a better way first.

**Comment by charlieegan3** [comment]
> Shoehorning linter violations in there would be a huge hack, but...

https://github.com/StyraInc/regal/pull/789 🎉
